### ISSUE TITLE
Demo application fails to build with meteor 1.4.3.1

### ISSUE THREAD

**Issue by janowsiany** [vazco/uniforms#220]
Demo application doesn't work after upgrading meteor to 1.4.3.1
```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /tools/fs/optimistic.js:204:17
    at wrap.makeCacheKey._len2 (/tools/fs/optimistic.js:22:15)
    at Entry._reallyRecompute (/home/jan/.meteor/packages/meteor-tool/.1.4.3_1.194k2uz++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:215:26)
    at Entry._recomputeIfDirty (/home/jan/.meteor/packages/meteor-tool/.1.4.3_1.194k2uz++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:179:17)
    at Entry.recompute (/home/jan/.meteor/packages/meteor-tool/.1.4.3_1.194k2uz++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:46:20)
    at optimistic (/home/jan/.meteor/packages/meteor-tool/.1.4.3_1.194k2uz++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/index.js:50:18)
    at /tools/isobuild/meteor-npm.js:478:31
    at /tools/isobuild/meteor-npm.js:491:9
    at Array.every (native)
    at /tools/isobuild/meteor-npm.js:488:30
    at /tools/isobuild/meteor-npm.js:491:9
    at Array.every (native)
    at /tools/isobuild/meteor-npm.js:488:30
    at /tools/isobuild/meteor-npm.js:284:9
    at Array.forEach (native)
    at Object.rebuildIfNonPortable (/tools/isobuild/meteor-npm.js:281:33)
    at /tools/isobuild/bundler.js:423:19
    at Function._.each._.forEach (/home/jan/.meteor/packages/meteor-tool/.1.4.3_1.194k2uz++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at Function.readDirsFromJSON (/tools/isobuild/bundler.js:422:9)
    at /tools/isobuild/isopack.js:1095:10
    at Array.forEach (native)
    at Function._.each._.forEach (/home/jan/.meteor/packages/meteor-tool/.1.4.3_1.194k2uz++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at [object Object]._.extend._loadUnibuildsFromPath (/tools/isobuild/isopack.js:965:7)
    at /tools/packaging/tropohouse.js:521:21
    at Array.forEach (native)
    at Function._.each._.forEach (/home/jan/.meteor/packages/meteor-tool/.1.4.3_1.194k2uz++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/packaging/tropohouse.js:520:13
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/packaging/tropohouse.js:515:22
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at Object.download (/tools/packaging/tropohouse.js:427:20)
    at /tools/packaging/tropohouse.js:600:22
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at [object Object]._.extend.downloadPackagesMissingFromMap (/tools/packaging/tropohouse.js:597:20)
    at /tools/project-context.js:808:25
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/project-context.js:807:20
    at /tools/packaging/catalog/catalog.js:100:5
    at /tools/utils/buildmessage.js:271:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
    at ProjectContext._downloadMissingPackages (/tools/project-context.js:806:13)
    at /tools/project-context.js:283:9
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._.extend._completeStagesThrough (/tools/project-context.js:273:18)
    at /tools/project-context.js:265:12
    at Function.run (/tools/tool-env/profile.js:490:12)
    at ProjectContext._.extend.prepareProjectForBuild (/tools/project-context.js:264:13)
    at /tools/runners/run-app.js:549:29
    at /tools/utils/buildmessage.js:271:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundleApp (/tools/runners/run-app.js:548:31)
    at [object Object]._.extend._runOnce (/tools/runners/run-app.js:617:35)
    at [object Object]._.extend._fiber (/tools/runners/run-app.js:876:28)
    at /tools/runners/run-app.js:403:12
```
[This issue](https://github.com/meteor/meteor/issues/8427#issuecomment-282578880) might have an explanation.
Currently we are using `kadira:flow-router-ssr` so probably the solution for this might be switching to react-router in the demo app? Do we need ssr there? @radekmie what do you think about this?

**Comment by janowsiany** [comment]
Closing this issue after rethinking and discussion as it is not a bug in this package.
