### ISSUE TITLE
problem running demo

### ISSUE THREAD

**Issue by sw-yx** [vazco/uniforms#322]
```
> @ start /Users/swyx/Desktop/webdev/testbeds/uniforms/demo
> meteor run

[[[[[ ~/Desktop/webdev/testbeds/uniforms/demo ]]]]]

=> Started proxy.                             
=> Meteor 1.5.1 is available. Update this project with 'meteor update'.
=> Started MongoDB.                           
                                                                                   
Unable to resolve some modules:

  "indexof" in /Users/swyx/Desktop/webdev/testbeds/uniforms/demo/node_modules/component-classes/index.js (web.browser)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save indexof           
                                              
W20170727-10:39:21.002(-4)? (STDERR) /Users/swyx/.meteor/packages/meteor-tool/.1.5.0.14k1pl1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170727-10:39:21.324(-4)? (STDERR) 						throw(ex);
W20170727-10:39:21.325(-4)? (STDERR) 						^
W20170727-10:39:21.326(-4)? (STDERR) 
W20170727-10:39:21.327(-4)? (STDERR) Error: Cannot find module 'uniforms/BaseField'
W20170727-10:39:21.328(-4)? (STDERR)     at Function.Module._resolveFilename (module.js:325:15)
W20170727-10:39:21.328(-4)? (STDERR)     at Function.Module._load (module.js:276:25)
W20170727-10:39:21.329(-4)? (STDERR)     at Module.require (module.js:353:17)
W20170727-10:39:21.330(-4)? (STDERR)     at require (internal/module.js:12:17)
W20170727-10:39:21.331(-4)? (STDERR)     at Object.<anonymous> (/Users/swyx/Desktop/webdev/testbeds/uniforms/packages/uniforms-antd/AutoField.js:23:19)
W20170727-10:39:21.331(-4)? (STDERR)     at Module._compile (module.js:409:26)
W20170727-10:39:21.332(-4)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20170727-10:39:21.333(-4)? (STDERR)     at Module.load (module.js:343:32)
W20170727-10:39:21.333(-4)? (STDERR)     at Function.Module._load (module.js:300:12)
W20170727-10:39:21.334(-4)? (STDERR)     at Module.require (module.js:353:17)
W20170727-10:39:21.334(-4)? (STDERR)     at require (internal/module.js:12:17)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.                                              
```

**Comment by radekmie** [comment]
Hi, @sw-yx. Yeah, I also saw that. It seems that Lerna still have problems with npm 5. As a workaround try `meteor npm install` instead of plain `npm install`.

**Comment by sw-yx** [comment]
no dice...

```
Shawns-MacBook-Air:demo swyx$ meteor npm i
lodash.clonedeep@4.5.0 node_modules/uniforms/node_modules/lodash.clonedeep -> node_modules/lodash.clonedeep
lodash.isequal@4.5.0 node_modules/uniforms/node_modules/lodash.isequal -> node_modules/lodash.isequal
lodash.set@4.3.2 node_modules/uniforms/node_modules/lodash.set -> node_modules/lodash.set
lodash.xorwith@4.5.0 node_modules/uniforms/node_modules/lodash.xorwith -> node_modules/lodash.xorwith
/Users/swyx/Desktop/webdev/testbeds/uniforms/demo
└─┬ meteor-node-stubs@0.2.11
  ├── process-nextick-args@1.0.7 
  ├─┬ readable-stream@2.2.10 (git+https://github.com/meteor/readable-stream.git#2e9112d7d31a2af6e0682db0e18679b1e5fd4694)
  │ ├── process-nextick-args@1.0.7  deduped
  │ └── util-deprecate@1.0.2  deduped
  └── util-deprecate@1.0.2 

Shawns-MacBook-Air:demo swyx$ npm start

> @ start /Users/swyx/Desktop/webdev/testbeds/uniforms/demo
> meteor run

[[[[[ ~/Desktop/webdev/testbeds/uniforms/demo ]]]]]

=> Started proxy.                             
=> Meteor 1.5.1 is available. Update this project with 'meteor update'.
=> Started MongoDB.                           
W20170727-18:55:52.315(-4)? (STDERR) /Users/swyx/.meteor/packages/meteor-tool/.1.5.0.14k1pl1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170727-18:55:52.527(-4)? (STDERR) 						throw(ex);
W20170727-18:55:52.528(-4)? (STDERR) 						^
W20170727-18:55:52.529(-4)? (STDERR) 
W20170727-18:55:52.530(-4)? (STDERR) Error: Cannot find module 'uniforms/BaseField'
W20170727-18:55:52.530(-4)? (STDERR)     at Function.Module._resolveFilename (module.js:325:15)
W20170727-18:55:52.531(-4)? (STDERR)     at Function.Module._load (module.js:276:25)
W20170727-18:55:52.532(-4)? (STDERR)     at Module.require (module.js:353:17)
W20170727-18:55:52.532(-4)? (STDERR)     at require (internal/module.js:12:17)
W20170727-18:55:52.533(-4)? (STDERR)     at Object.<anonymous> (/Users/swyx/Desktop/webdev/testbeds/uniforms/packages/uniforms-antd/AutoField.js:23:19)
W20170727-18:55:52.533(-4)? (STDERR)     at Module._compile (module.js:409:26)
W20170727-18:55:52.534(-4)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20170727-18:55:52.534(-4)? (STDERR)     at Module.load (module.js:343:32)
W20170727-18:55:52.535(-4)? (STDERR)     at Function.Module._load (module.js:300:12)
W20170727-18:55:52.535(-4)? (STDERR)     at Module.require (module.js:353:17)
W20170727-18:55:52.536(-4)? (STDERR)     at require (internal/module.js:12:17)
=> Exited with code: 1

```

**Comment by radekmie** [comment]
Have you run it with no `node_modules`?

**Comment by sw-yx** [comment]
hey sorry for the delay. removing `node_modules` and running `meteor npm install` works! might want to put that in the instructions

**Comment by radekmie** [comment]
I've already did.
