### ISSUE TITLE
JSONSchema bridge fails on object that is using allOf + #ref

### ISSUE THREAD

**Issue by hmvp** [vazco/uniforms#722]
When adding the following test in `packages/uniforms-bridge-json-schema/__tests__/JSONSchemaBridge.ts`:
```js
    it('returns correct definition (allOf with $ref)', () => {
      expect(bridge.getField('shippingAddress.street')).toEqual({
        type: 'string',
      });
    });
```
It fails with:
```Summary of all failing tests
 FAIL  packages/uniforms-bridge-json-schema/__tests__/JSONSchemaBridge.ts
  ● JSONSchemaBridge › #getField › returns correct definition (allOf with $ref)

    Invariant Violation: Field not found in schema: "shippingAddress.street"

      162 |       }
      163 | 
    > 164 |       invariant(definition, 'Field not found in schema: "%s"', name);
          |       ^
      165 | 
      166 |       if (definition.$ref) {
      167 |         definition = resolveRef(definition.$ref, this.schema);

      at invariant (node_modules/invariant/invariant.js:40:15)
      at packages/uniforms-bridge-json-schema/src/JSONSchemaBridge.ts:164:7
          at Array.reduce (<anonymous>)
      at JSONSchemaBridge.reduce [as getField] (packages/uniforms-bridge-json-schema/src/JSONSchemaBridge.ts:123:33)
      at Object.getField (packages/uniforms-bridge-json-schema/__tests__/JSONSchemaBridge.ts:334:21)

```
I expect it to work and also see this happen while trying to implement uniform with a schema generated by [pydantic](pydantic-docs.helpmanual.io)

**Comment by hmvp** [comment]
Happens both in v2 and in v3

**Comment by Monteth** [comment]
Hi @hmvp,
Thank you for reporting, I'll take care of it.
